package pl.lodz.p.microservices.proxy.mongo;

enum Methods {
    GET_ROOMS_LIST_FROM_DATABASE,
    GET_ROOM_DETAILS_FROM_DATABASE,
    SAVE_NEW_ROOM_IN_DATABASE,
    DELETE_ROOM_FROM_DATABASE,
    EDIT_ROOM_IN_DATABASE
}